/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SONY
 */
public class list_branches1 extends javax.swing.JFrame {

    /**
     * Creates new form list_branches1
     */
    public list_branches1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton5.setText("<- Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton4.setText("MbaTech 2nd Yr CS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton3.setText("Mbatech 3rd Yr CS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("Btech 3rd Yr CS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setText("Btech 2nd Yr CS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Select the branch for which  you want to prepare time table :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(450, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(450, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            ResultSet rs=Teacher.fetchResult("b3CS");
            for (int i = 0; rs.next(); i++) {
                b3teacher.tArray[i]=rs.getString(1)+" "+rs.getString(2);
                b3teacher.tCount[i]=rs.getInt(3);
                System.out.println(b3teacher.tArray[i]+b3teacher.tCount[i]);
            }
             b3teacher.t1_count=b3teacher.tCount[0];
             b3teacher.t2_count=b3teacher.tCount[1];
             b3teacher.t3_count=b3teacher.tCount[2];
             b3teacher.t4_count=b3teacher.tCount[3];
             b3teacher.t5_count=b3teacher.tCount[4];
             b3teacher.t6_count=b3teacher.tCount[5];
             b3teacher.t7_count=b3teacher.tCount[6];
             b3teacher.t8_count=b3teacher.tCount[7];
             
        } catch (SQLException ex) {
            Logger.getLogger(list_branches1.class.getName()).log(Level.SEVERE, null, ex);
        }
        practice1 p1=new practice1();
        p1.setVisible(true);
        list_branches1.this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        second s1=new second();
        s1.setVisible(true);
        list_branches1.this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
            ResultSet rs=Teacher.fetchResult("b2CS");
            for (int i = 0; rs.next(); i++) {
                b2teacher.tArray[i]=rs.getString(1)+rs.getString(2);
                b2teacher.tCount[i]=rs.getInt(3);
                System.out.println(b2teacher.tArray[i]+b2teacher.tCount[i]);
            }
             b2teacher.t1_count=b2teacher.tCount[0];
             b2teacher.t2_count=b2teacher.tCount[1];
             b2teacher.t3_count=b2teacher.tCount[2];
             b2teacher.t4_count=b2teacher.tCount[3];
             b2teacher.t5_count=b2teacher.tCount[4];
             b2teacher.t6_count=b2teacher.tCount[5];
             b2teacher.t7_count=b2teacher.tCount[6];
             b2teacher.t8_count=b2teacher.tCount[7];
             
        } catch (SQLException ex) {
            Logger.getLogger(list_branches1.class.getName()).log(Level.SEVERE, null, ex);
        }
        practice2 p1=new practice2();
        p1.setVisible(true);
        list_branches1.this.setVisible(false);               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
            ResultSet rs=Teacher.fetchResult("m3CS");
            for (int i = 0; rs.next(); i++) {
                m3teacher.tArray[i]=rs.getString(1)+rs.getString(2);
                m3teacher.tCount[i]=rs.getInt(3);
                System.out.println(m3teacher.tArray[i]+m3teacher.tCount[i]);
            }
             m3teacher.t1_count=m3teacher.tCount[0];
             m3teacher.t2_count=m3teacher.tCount[1];
             m3teacher.t3_count=m3teacher.tCount[2];
             m3teacher.t4_count=m3teacher.tCount[3];
             m3teacher.t5_count=m3teacher.tCount[4];
             m3teacher.t6_count=m3teacher.tCount[5];
             m3teacher.t7_count=m3teacher.tCount[6];
             m3teacher.t8_count=m3teacher.tCount[7];
             
        } catch (SQLException ex) {
            Logger.getLogger(list_branches1.class.getName()).log(Level.SEVERE, null, ex);
        }
        practice3 p1=new practice3();
        p1.setVisible(true);
        list_branches1.this.setVisible(false);  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try {
            ResultSet rs=Teacher.fetchResult("m2CS");
            for (int i = 0; rs.next(); i++) {
                m2teacher.tArray[i]=rs.getString(1)+rs.getString(2);
                m2teacher.tCount[i]=rs.getInt(3);
                System.out.println(m2teacher.tArray[i]+m2teacher.tCount[i]);
            }
             m2teacher.t1_count=m2teacher.tCount[0];
             m2teacher.t2_count=m2teacher.tCount[1];
             m2teacher.t3_count=m2teacher.tCount[2];
             m2teacher.t4_count=m2teacher.tCount[3];
             m2teacher.t5_count=m2teacher.tCount[4];
             m2teacher.t6_count=m2teacher.tCount[5];
             m2teacher.t7_count=m2teacher.tCount[6];
             m2teacher.t8_count=m2teacher.tCount[7];
             
        } catch (SQLException ex) {
            Logger.getLogger(list_branches1.class.getName()).log(Level.SEVERE, null, ex);
        }
        practice4 p1=new practice4();
        p1.setVisible(true);
        list_branches1.this.setVisible(false);  
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list_branches1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list_branches1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list_branches1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list_branches1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list_branches1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
